site_name: µVox docs
site_description: Hardware & Software Wiki for the µVox open-source amplifier
site_url: https://docs.muvox.io
repo_name: 'muvox-io/docs.muvox.io'
repo_url: 'https://github.com/muvox-io/docs.muvox.io'
edit_uri: 'https://github.com/muvox-io/docs.muvox.io/tree/master/docs'
docs_dir: docs
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      lang:
        - en
theme:
  name: material
  language: 'en'
#  # custom_dir: 'overrides'
  logo: 'images/euph.svg'
#  favicon: _media/favicon.ico
  palette:
    - scheme: muvox
      accent: indigo

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - navigation.tracking
  font:
    text: Barlow
    code: Roboto Mono

markdown_extensions:
  - admonition
  - toc:
      permalink: "~"
      toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tilde
  - meta
  - def_list
  - attr_list

nav:
  - Home:
      - 'index.md'
  - Hardware:
      - 'hardware/index.md'
  - Software:
      - 'software/index.md'
  - For Developers:
      - 'for-developers/index.md'
      - Development environment: 'for-developers/dev-environment.md'
  - Get Help:
      - 'help/index.md'
